name = "astro"
account_id = "fb6f0b1d5781a11c11438587082cd67b"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist/client"

[[kv_namespaces]]
binding = "STORE_KV"
id = "ccbe577271c442c896598eace43681a1"

[[kv_namespaces]]
binding = "SESSION"
id = "6efe66970eb641ed973f8f2a3d094d6f"
